spring:
  application:
    name: spring-study-roadmap

  datasource:
    url: jdbc:mariadb://localhost:3306/basic
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update  # 애플리케이션 실행 시 테이블 자동 생성
    show-sql: true      # 실행되는 SQL 로그 출력
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect