spring:
  application:
    name: spring-study-roadmap

  datasource:
    url: jdbc:mariadb://localhost:3306/study_link
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

jwt:
  secret: qwF0r-hPgW301pEr756XZ2EVMz4zFH1hBawdJY92DQg
  expiration: 3600000